apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vu9rm2opl-nodejs
  janus-idp.io/tekton: vu9rm2opl-nodejs
  backstage.io/kubernetes-id: vu9rm2opl-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vu9rm2opl-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
