apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: vu9rm2opl-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vu9rm2opl-nodejs 
  name: vu9rm2opl-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: vu9rm2opl-nodejs 
